services:
  hasher:
    deploy:
      placement:
        constraints:
        - node.role == worker
      replicas: 1
      restart_policy:
        condition: any
    image: dockercoins/hasher:v0.2
  redis:
    deploy:
      placement:
        constraints:
        - node.role == worker
      replicas: 1
      restart_policy:
        condition: any
    image: redis
  rng:
    deploy:
      mode: global
      placement:
        constraints:
        - node.role == worker
      restart_policy:
        condition: any
    image: dockercoins/rng:v0.2
  webui:
    deploy:
      placement:
        constraints:
        - node.role == worker
      replicas: 1
      restart_policy:
        condition: any
    image: dockercoins/webui:v0.2
    ports:
    - "30001:80"
  worker:
    deploy:
      placement:
        constraints:
        - node.role == worker
      replicas: 1
      restart_policy:
        condition: any
    image: dockercoins/worker:v0.2
version: "3.8"
