version: "3"

services:

  rng:
    image: secobau/dockercoins-rng:release-1.1
    deploy:
      mode: global
      placement:
        constraints:
        - node.role == worker

  hasher:
    image: secobau/dockercoins-hasher:release-1.1
    deploy:
      placement:
        constraints:
        - node.role == worker

  webui:
    image: secobau/dockercoins-webui:release-1.1
    ports:
    - "8888:80"
    deploy:
      placement:
        constraints:
        - node.role == worker

  redis:
    image: redis
    deploy:
      placement:
        constraints:
        - node.role == worker

  worker:
    image: secobau/dockercoins-worker:release-1.1
    deploy:
      replicas: 3 #Change to 21 to improve performance in 7x
      placement:
        constraints:
        - node.role == worker
