version: "3"
services:
  php:
    image: secobau/php:apache
    networks:
      - frontend
    deploy:
      replicas: 4
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "0.06"
          memory: 60M
    ports:
      - "80:80"
    # echo "Alaska2017" | docker secret create SA_PASSWORD -
    environment:
      SA_PASSWORD: "/run/secrets/SA_PASSWORD"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: echo $SA_PASSWORD | tee /tmp/test 
networks:
  frontend:
