version: "3"
services:
  php:
    image: secobau/php:apache
    networks:
      - frontend
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "0.06"
          memory: 60M
    ports:
      - "80:80"
    # echo "Alaska2017" | tee ./my_secret.txt
    environment:
      SA_PASSWORD: "/run/secrets/my_secret"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: echo $( cat /run/secrets/my_secret ) | tee /tmp/test 
    secrets:
      - my_secret
networks:
  frontend:
secrets:
  my_secret:
    file: ./my_secret.txt
  
